# Generated by Django 5.1.6 on 2025-03-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
