# Generated by Django 5.1.6 on 2025-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0002_milkrecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(blank=True, choices=[('M', 'Morning'), ('E', 'Evening')], default='', max_length=1),
        ),
    ]
