# Generated by Django 5.1.6 on 2025-03-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0003_alter_milkrecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
