# Generated by Django 5.1.6 on 2025-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0005_alter_milkrecord_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='fat_value',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='rate_per_liter',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
