# Generated by Django 5.1.6 on 2025-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0006_alter_milkrecord_fat_value_alter_milkrecord_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
