# Generated by Django 5.1.6 on 2025-03-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0007_customer_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='serial_number',
        ),
    ]
