# Generated by Django 5.1.6 on 2025-03-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0008_remove_customer_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1),
        ),
    ]
