# Generated by Django 5.1.6 on 2025-03-19 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0009_alter_milkrecord_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rate_per_liter_person',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6),
        ),
    ]
