# Generated by Django 5.1.6 on 2025-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0011_remove_milkrecord_rate_per_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='rate_per_liter',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
