# Generated by Django 5.1.6 on 2025-03-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk_management', '0012_milkrecord_rate_per_liter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkrecord',
            name='rate_per_liter',
        ),
    ]
